if (typeof define !== 'function') {
    var define = function(callback) {
        module.exports = callback();
    };
}

define(function() {
    return    {
        'name': 'IRELAND',
        'type': 'ENodeBFunction',
        'poId': '281474976751638',
        'fdn': 'MeContext=EARTH,ManagedElement=EUROPE,ENodeBFunction=IRELAND',
        'attributes': [{
            'key': 'nnsfMode',
            'value': 'RPLMN_IF_SAME_AS_SPLMN'
        }, {
            'key': 'sctpRef',
            'value': null
        }, {
            'key': 'x2WhiteList',
            'value': null
        }, {
            'key': 'tHODataFwdReordering',
            'value': 50
        }, {
            'key': 'pmHwUtilDl',
            'value': null
        }, {
            'key': 'zzzTemporary9',
            'value': -2000000000
        }, {
            'key': 'pmZtemporary34',
            'value': null
        }, {
            'key': 'ENodeBFunctionId',
            'value': 'IRELAND'
        }, {
            'key': 'eNodeBPlmnId',
            'value': null
        }, {
            'key': 'zzzTemporary7',
            'value': ''
        }, {
            'key': 'pmZtemporary35',
            'value': null
        }, {
            'key': 'dscpLabel',
            'value': 24
        }, {
            'key': 'zzzTemporary8',
            'value': ''
        }, {
            'key': 'userLabel',
            'value': ''
        }, {
            'key': 'pmHwUtilUl',
            'value': null
        }, {
            'key': 'rrcConnReestActive',
            'value': false
        }, {
            'key': 'dnsLookupOnTai',
            'value': 'ON'
        }, {
            'key': 'x2retryTimerStart',
            'value': 30
        }, {
            'key': 'upIpAccessHostRef',
            'value': null
        }, {
            'key': 'ulTransNwBandwidth',
            'value': 1000
        }, {
            'key': 'ulAccGbrAdmThresh',
            'value': 1000
        }, {
            'key': 'dlTransNwBandwidth',
            'value': 1000
        }, {
            'key': 'timeAndPhaseSynchCritical',
            'value': false
        }, {
            'key': 'schedulingStrategy',
            'value': 'ROUND_ROBIN'
        }, {
            'key': 'ulSchedulerDynamicBWAllocationEnabled',
            'value': true
        }, {
            'key': 'oaMLinkSuperVisionActive',
            'value': true
        }, {
            'key': 'zzzTemporary2',
            'value': ''
        }, {
            'key': 'zzzTemporary1',
            'value': ''
        }, {
            'key': 'dnsLookupTimer',
            'value': 0
        }, {
            'key': 'pmPdcpPktDiscDlEth',
            'value': null
        }, {
            'key': 'zzzTemporary4',
            'value': ''
        }, {
            'key': 'zzzTemporary3',
            'value': ''
        }, {
            'key': 'collectLogsStatus',
            'value': null
        }, {
            'key': 'zzzTemporary6',
            'value': ''
        }, {
            'key': 'zzzTemporary10',
            'value': -2000000000
        }, {
            'key': 's1RetryTimer',
            'value': 30
        }, {
            'key': 'x2BlackList',
            'value': null
        }, {
            'key': 'zzzTemporary5',
            'value': ''
        }, {
            'key': 'zzzTemporary11',
            'value': -2000000000
        }, {
            'key': 'zzzTemporary12',
            'value': -2000000000
        }, {
            'key': 'collectTraceStatus',
            'value': null
        }, {
            'key': 'x2IpAddrViaS1Active',
            'value': true
        }, {
            'key': 'dlAccGbrAdmThresh',
            'value': 1000
        }, {
            'key': 'eNBId',
            'value': -1
        }, {
            'key': 'x2retryTimerMaxAuto',
            'value': 1440
        }
        ],
        'childrens': null
    };


});
