define([], function() {
    return {
        moPrimaryTypeAttributesResponse: {
            'name': '1',
            'type': 'stub-router',
            'writeBehavior': 'NOT_ALLOWED',
            'poId': 281474982707498,
            'fdn': 'MeContext=SPFRER60001,ManagedElement=SPFRER60001,contexts=1,context=SIMPLE_CONTEXT,router=ospfRouter,ospf=1,stub-router=1',
            'namespace': 'DRAFT:urn:com:ericsson:yang:ericsson-ipos-ospf',
            'namespaceVersion': '2015.9.8',
            'attributes': [
                {
                    'key': 'stub-router-key',
                    'value': '1',
                    'datatype': null
                },
                {
                    'key': 'strict-bgp-tracking',
                    'value': null,
                    'datatype': null
                }
            ]
        },
        moPrimaryModelDefinition: {
            'moType': 'stub-router',
            'attributes': [
                {
                    'key': 'strict-bgp-tracking',
                    'writeBehavior': 'PERSIST_AND_DELEGATE',
                    'readBehavior': 'FROM_PERSISTENCE',
                    'userExposure': 'ALWAYS',
                    'immutable': false,
                    'type': 'BOOLEAN',
                    'constraints': {
                        'nullable': true
                    },
                    'activeChoiceCase': {
                        'caseName': 'strict-bgp-tracking',
                        'choiceName': 'stub-router-opt'
                    },
                    'defaultValue': null,
                    'description': 'type empty',
                    'namespaceversions': {
                        'DRAFT:urn:com:ericsson:yang:ericsson-ipos-ospf': [
                            '2015.9.8'
                        ]
                    }
                },
                {
                    'key': 'stub-router-key',
                    'writeBehavior': 'PERSIST_AND_DELEGATE',
                    'readBehavior': 'FROM_PERSISTENCE',
                    'userExposure': 'ALWAYS',
                    'immutable': true,
                    'type': 'STRING',
                    'constraints': {
                        'nullable': false,
                        'valueRangeConstraints': null,
                        'validContentRegex': null
                    },
                    'activeChoiceCase': null,
                    'defaultValue': null,
                    'description': 'Autogenerated Key do not remove',
                    'namespaceversions': {
                        'DRAFT:urn:com:ericsson:yang:ericsson-ipos-ospf': [
                            '2015.9.8'
                        ]
                    }
                }
            ],
            'choices': [
                {
                    'name': 'stub-router-opt',
                    'mandatory': false,
                    'cases': [
                        {
                            'name': 'bgp-converge-delay',
                            'attributes': [],
                            'primaryType': true,
                            'description': 'bgp-converge-delay case'
                        },
                        {
                            'name': 'on-startup',
                            'attributes': [],
                            'primaryType': true,
                            'description': 'on-startup case'
                        },
                        {
                            'name': 'strict-bgp-tracking',
                            'attributes': [
                                {
                                    'name': 'strict-bgp-tracking'
                                }
                            ],
                            'primaryType': false,
                            'description': 'strict-bgp-tracking case'
                        }
                    ]
                }
            ]
        },
        moPrimaryTypeSaveResponse: {
            'poId': 281474982707498,
            'fdn': 'MeContext=SPFRER60001,ManagedElement=SPFRER60001,contexts=1,context=SIMPLE_CONTEXT,router=ospfRouter,ospf=1,stub-router=1',
            'attributes': [
                {
                    'key': 'strict-bgp-tracking',
                    'value': false,
                    'datatype': 'BOOLEAN'
                }
            ]
        },
        moNoPrimaryTypeAttributesResponse: {
            'name': '1',
            'type': 'stub-router',
            'poId': 281474982707498,
            'fdn': 'MeContext=SPFRER60001,ManagedElement=SPFRER60001,contexts=1,context=SIMPLE_CONTEXT,router=ospfRouter,ospf=1,stub-router=1',
            'namespace': 'DRAFT:urn:com:ericsson:yang:ericsson-ipos-ospf',
            'namespaceVersion': '2015.9.8',
            'attributes': [
                {
                    'key': 'stub-router-key',
                    'value': '1',
                    'datatype': null
                },
                {
                    'key': 'strict-bgp-tracking',
                    'value': true,
                    'datatype': null
                }
            ]
        },
        moNoPrimaryModelDefinition: {
            'moType': 'stub-router',
            'writeBehavior': 'NOT_ALLOWED',
            'attributes': [
                {
                    'key': 'strict-bgp-tracking',
                    'writeBehavior': 'PERSIST_AND_DELEGATE',
                    'readBehavior': 'FROM_PERSISTENCE',
                    'userExposure': 'ALWAYS',
                    'immutable': false,
                    'type': 'BOOLEAN',
                    'constraints': {
                        'nullable': true
                    },
                    'activeChoiceCase': {
                        'caseName': 'strict-bgp-tracking',
                        'choiceName': 'stub-router-opt'
                    },
                    'defaultValue': null,
                    'description': 'type empty',
                    'namespaceversions': {
                        'DRAFT:urn:com:ericsson:yang:ericsson-ipos-ospf': [
                            '2015.9.8'
                        ]
                    }
                },
                {
                    'key': 'stub-router-key',
                    'writeBehavior': 'PERSIST_AND_DELEGATE',
                    'readBehavior': 'FROM_PERSISTENCE',
                    'userExposure': 'ALWAYS',
                    'immutable': true,
                    'type': 'STRING',
                    'constraints': {
                        'nullable': false,
                        'valueRangeConstraints': null,
                        'validContentRegex': null
                    },
                    'activeChoiceCase': null,
                    'defaultValue': null,
                    'description': 'Autogenerated Key do not remove',
                    'namespaceversions': {
                        'DRAFT:urn:com:ericsson:yang:ericsson-ipos-ospf': [
                            '2015.9.8'
                        ]
                    }
                }
            ],
            'choices': [
                {
                    'name': 'stub-router-opt',
                    'mandatory': false,
                    'cases': [
                        {
                            'name': 'bgp-converge-delay',
                            'attributes': [],
                            'primaryType': false,
                            'description': 'bgp-converge-delay case'
                        },
                        {
                            'name': 'on-startup',
                            'attributes': [],
                            'primaryType': false,
                            'description': 'on-startup case'
                        },
                        {
                            'name': 'strict-bgp-tracking',
                            'attributes': [
                                {
                                    'name': 'strict-bgp-tracking'
                                }
                            ],
                            'primaryType': false,
                            'description': 'strict-bgp-tracking case'
                        }
                    ]
                }
            ]
        },
        moCommonNonPersistAttributesResponse: {

            'moType': 'stub-router',
            'attributes': []
        }
    };


});
