define(function() {
    return [
        {
            key: 'stub-router-opt',
            type: 'CHOICE',
            defaultValue: null,
            value: 'strict-bgp-tracking',
            selectedIndex: 2,
            mandatory: false,
            expanded: true,
            cases: [
                {
                    name: 'bgp-converge-delay',
                    attributes: [],
                    hasPrimaryType: true,
                    description: 'Active on startup until timer expires or BGP converges '
                },
                {
                    name: 'on-startup',
                    attributes: [],
                    hasPrimaryType: true,
                    description: 'Active on startup until timer expires'
                },
                {
                    name: 'strict-bgp-tracking',
                    attributes: [
                        {
                            activeChoiceCase: {
                                caseName: 'strict-bgp-tracking',
                                choiceName: 'stub-router-opt'
                            },
                            key: 'attrs-strict-bgp-tracking',
                            readOnly: false,
                            constraints: {
                                nullable: true
                            },
                            type: 'BOOLEAN',
                            defaultValue: null,
                            description: 'Active whenever BGP has not converged',
                            isNonPersistent: false,
                            value: true,
                            inputTitle: 'Type: BOOLEAN'
                        }
                    ],
                    hasPrimaryType: false,
                    description: 'strict-bgp-tracking'
                }
            ],
            isArray: true,
            widgetsProducer: {},
            inputTitle: 'stub-router-opt'
        },
        {
            activeChoiceCase: null,
            key: 'stub-router-key',
            readOnly: true,
            constraints: {
                nullable: false,
                valueRangeConstraints: null,
                validContentRegex: null
            },
            type: 'STRING',
            defaultValue: null,
            description: 'Autogenerated Key do not remove',
            isNonPersistent: false,
            value: '1',
            widgetsProducer: {},
            expanded: false,
            inputTitle: 'Type: STRING, ReadOnly: True',
            itemsNew: {
                key: 'stub-router-key',
                description: 'Autogenerated Key do not remove',
                value: '1'
            }
        }
    ];
});
